### ISSUE TITLE
Windows 11 feedback

### ISSUE THREAD

**Issue by dannymcgee** [tauri-apps/tauri-plugin-vibrancy#3]
I don't see a Discussions tab in this repo, but feel free to redirect me if this should be posted elsewhere.

1. Using `apply_blur`, the effect is much less strong than what's typical in first-party Windows apps. Here's a comparison between Tauri on the left and the built-in calculator app on the right.

![tauri-vibrancy-vs-winui-acrylic](https://user-images.githubusercontent.com/13191586/145120915-8fd073b9-a5f8-43f5-925c-c3913c82b733.jpg)

I took a peek at your code, but I don't see where this would even be configurable in the Windows APIs you're using, so I have no idea if this is fixable, just figured I'd mention it. As it stands, the blur effect is not really strong enough to be useful (IMO), since the background is sharp enough to interfere with the legibility of the foreground app.
2. If I move the Tauri window around while there's an Explorer window behind it, whatever is immediately behind the Explorer's header area flickers into view every so often, like there's some Z-fighting type of thing happening.

**Comment by amrbashir** [comment]
> Using apply_blur, the effect is much less strong than what's typical in first-party Windows apps. Here's a comparison between Tauri on the left and the built-in calculator app on the right.

I am still on win10, haven't upgraded to win11 yet and I am not sure what material or api the calculator is using tbh. AFAIK, the api that I use doesn't support specifying how strong the blur is, but it can change the color of the window (with alpha values), which I plan on adding later.

> As it stands, the blur effect is not really strong enough to be useful (IMO), since the background is sharp enough to interfere with the legibility of the foreground app.

That's true, I suggest either you wait for `apply_mica()` when it is implemented or decrease your background color opacity until you get enough contrast.

> 2. If I move the Tauri window around while there's an Explorer window behind it, whatever is immediately behind the Explorer's header area flickers into view every so often, like there's some Z-fighting type of thing happening.

Can you please record it ?

**Comment by dannymcgee** [comment]
> Can you please record it ?

Sure, here's the link: https://www.youtube.com/watch?v=DdIpEREndfE

**Comment by amrbashir** [comment]
Thanks, I don't think there is much for me to do there tbh, it seems like a bug in the OS itself.

**Comment by amrbashir** [comment]
Now that I have upgraded to Win11, I found out that the calculator app is using Mica material and not BlurBehind, hence the difference in blur strength. I will be providing a method to apply Mica material once it has a stable api for it, subscribe to #1 to get notified when it is done.

I also checked the glitch that happens when moving a BlurBehind window over Mica and as I said earlier, it is something in the Windows compositor and I don't think I can fix that.

I am gonna go ahead and close this issue, let me know if you need anything else.

**Comment by tropicaaal** [comment]
Also, just to clarify. In your original screenshot, you were using the pre-redesign version of calculator that uses acrylic in it's background, not Mica. So if you're looking for parity with that, use the acrylic options available.
